namespace DuneEdit.Core;

/// <summary>Maps Dune's flat map coordinates to the original game's spice-field zones.</summary>
public static class MapZones
{
    public const int Width = 256;
    public const int Height = 151;

    private static readonly byte[] CellsData = Decode();

    // MAP2.HSQ stores the field id for each globe sample. TABLAT.BIN maps signed
    // latitude to its variable-width row. These cells are the 8-bit flat-map
    // projection reconstructed from DUNEPRG.EXE routines 100D:B58B and 100D:B5C5.
    private const string EncodedRuns =
        """
        HhUHNBEABDQtH5UAAxUBAB8VBjQOAAo0MB8yAAhGVQADFQEAHhUINAgAETQvHy4ADkZQAAUVAQAeFQk0BQAWNC4fIgALNhBGJwAGRyEABBUBAB8VIjQDIzQf
        FgAONhNGHwATRxoABBUBAB0VIDQHIzQfEwAONhZGHQAZRxMABhgBFQEAAhgcFR40CyM0Hx42FkYYAAE8IUcMAAoYAQAHGBYaHTQNIzAfITYbRhIABTwmRw8Y
        AQAHGBcaGTQRIy4fITYhRgsACTwkRw8YAQAHGBYaGDQTIy4fIDYkRggACzwiRxAYAQAIGBUaFjQWIywfITYmRhI8IUcQGAEACBgVGhQ0GSMqHyE2KUYSPB5H
        ERgBAAkYGRoPMRojKR8iNihGEzwdRxEYAQAKGBcaETEaIycfIjYpRhQ8G0cSGAEAChgXGhMxGCMnHyE2KkYWPBhHExgBAAoYGBoSMRgjJh8hNitGGDwWRxMY
        AQAKGBgaFDEWIyUfITYBQStGGDwWRxMYAQALGBcaFDEXIyQfGzYHLgdBBz8dRhc8AjcURxQYAQALGBgaFTEUIyIfAywYNgkuCUELPxhGFjwGNxFHFBgBAAwY
        FxQVMRUjHR8HLBc2Ci4KQQ4/E0YWPAg3D0cVGAEACxgYFBcxEjMcHwksFTYKLg1BDz8RRhU8CzcMRwIRFBgBAAwYGBQVMRMzGR8NLBM2Cy4NQRE/EEYTPA43
        CUcEERQYDBgYFBUxFDMNJwkfECwRNgwuDUEVPwpGAkISPBI3BkcFERMYDBgYFBQxEzMQJwYfEywQNgwuDUEZPwRGBEIRPBM3BUcIEREYDRgYFBUxEjMPJwMf
        FywONg0uDUEbPwhCDjwXNwJHCxEOGAwYGBQVMRIzEicZLA02DS4NQRw/CEIMPBk3DRENGA0YGBQKEwoiETMUJxksDTYMLg1BHT8JQgo8GTcPEQsYDRIYFAoT
        CiIRMxYnGCwLNg0uDkEdPwpCBzwaNxURBRINEhgUChMKIhAzFycZLAk2DS4PQR0/AkoOQho3FhEFEhISExQKEwoiEDMZJxgsCDYOLg9BGz8EShBCEzcEPhYR
        BRITEgUUChANEwoiDzMaJxYsAykGNg8uEUEYPwZKEEIQNwY+FxEEEhMSBRQKEA0TCiIPMxonFCwGKQQ2EC4QQRg/CEoTQgo3CT4WEQQSExIFFAkQDhMKIg0z
        HScSLAgpAzYPLg9BGT8JShRCCDcJPhcRBBITEgUUChANEwoiDDMeJxEsCikCNgQeDC4OQRg/C0oVQgU3Cj4YEQMSFBIOEA0TCyIJMwNLHScPLA0pBR4NLgxB
        GT8MShZCAjcJPhoRAxITEhAQDBMLIgEzBxwGSxsnCiwRKQceDC4MQRg/DUoXQgk+HBECEhMSEBANEwoiCBwHSxonBywTKQoeCi4MQRg/DUoWQgk+HRECEhMS
        EBAMEwoiCRwJSxknBiwSKQseCi4NQRc/DkoVQgc+HxECEhQSDxAMEwoiBxwMSxcnBiwUKQseCS4OQRA6Bj8OShVCBT4iEQESExIQEAoTA0sPIg5LFicGLBUp
        Cx4ILg9BEDoFPw5KFUIFPiIRARITEhAQChMESw0iD0sXJwQsFykKHgguD0EQOgQ/DkoWQgM+JBEBEhQSEBAJEwZLDCIPSxYnBCwYKQkeCS4PQQ86EkoWQgQ+
        AQwjERQSEBAKEwZLByIUSxUnAywaKQgeCS4OQRA6EUoXQgQ+BQwCEQIMGxETEhEQChMHSwQiGEsTJwMsGikGHgIgCi4NQRA6EEoDOBVCBT4MDBcRFBIQEAoT
        I0sSJwUsGikEHgQgCS4OQQ86D0oEOBVCBT4MDBcRFBIQEAoTE0sIIQlLEScFLBopAh4GIAouDkEOOg5KBjgUQgY+CwwXERQSEBADEwYCEEsNIQlLECcFLBop
        CSAJLg9BDToNSgg4EkIIPgsMFhEUEg8QCwINSxAhCUsOJwUsGikLIAguD0ENOgxKCTgRQgo+CgwWEQEREhIKEAULDgIBKwlLEyEISwsnARsCJwUsGCkNIAku
        DkEMOgtKDDgQQgs+BwwXEQEREBIJEAcLDwICKwdLFSENSwkbBCwYKQ8gBi4OQRJIEzgOQg0+BgwXEQERDxIJEAcLEAIDKwRLFyEMSwsbAiwYKRMgAy4OQRJI
        FDgMQg8+BQwOEQUMBBEQCwkQBgsQAgUrAksZIQtLCxsCLBcpGCAMQRNIFTgJQhE+BAwNEQkMAgsRCwgQBgsQAgcrGSELSw4bFikYIAdIBUETSBY4B0IBRRE+
        BAwMEQoMAgsRCwcQBgsRAgcrGiENSwwbFCkaIAdIA0EUSBg4A0IDRRI+AwwLEQsMAgsCDBALBRAGCxECCisYIQ5LDRsRKRsgHkgbOARFET4EDAkRDgwCDBEL
        BBAFCxECCysZIQ5LDRsMKR8gHkgbOANFEj4EDAkRDgwDDBgLEQIMKxkhDksPGwYpIyAeSBw4AkUUPgIMCRENDAELAQsCDBkLEAINKxkhDksSGyUgHkgcOAJF
        FT4CDAYRDwwBCxsLEQIMKxkhASYPSxEbJSAeSBw4A0UUPhcMAQsbCxMCCysYIQImD0sRGyQgHkgcOANFFD4YDAEMGgsUAgorFyEDJhBLEBsjIBxIA0QbOARF
        FD4YDAIMGAsUAgsrFSEFJhBLEBsjIAEoF0gHRBk4BkUTPhkMAgwYCxQCCysOIQImBSEGJhBLEBshIAIoF0gIRBg4B0USPggMAw0ODAQMFgsRAgIkDSsIIQIr
        AyEDJgQhByYQSw8bISADKBdICEQWOAlFEj4GDAUNDQwCDAUKDwsVAgIkDSsFIQcrBSYCIQgmEUsOGyEgBCgWSAlEFDgLRRA+BgwHDQwMCAoFCwEIBQsBCBUC
        BSQNKwMhBysQJhJLDRsgIAYoFEgKRBI4DkUOPggMBg0KDAIKCQoCCwQIAgsDCAwCCQMFJBcrECYTSwwbHyAIKBNIC0QQOBBFDT4CFwcMBQ0GDAYKCQoLCAQC
        AwEEAgoDBiQWKxEmE0sLGx4gCSgUSApEDjgSRQw+BRcEDAMJAw0EDAgKCQoLCAICCAELAwckCCsCJAorEyYTSwobGyANKA5ICUAGRA04FEUKPggXAQwFCQIN
        DAoKCgoIAQIJAQsDCSQEKwYkBysUJhNLChsZIBAoC0gOQAJEDTgXRQg+CRcGCQ0KCgoKCAsBCwMJJAIrCCQGKxQmE0sKGxcgEygISBNADDgXRQg+ChcGCQwK
        CwoJCAsBDAMTJAUrFCYTSwobFiAVKAVIF0AKOBdFCT4LFwcJCQoLCgkICwEOAxEkAjIDKwIyEyYSSwobDCADLxwoA0gaQAk4F0ULPgkXCQkHCgsKCggIARAD
        ESQHMhMmD0sKGwcvCCADLxwoAkgcQAc4GEULPgoXCAkHCgsKDAgFAREDESQIMhImDUsJGwsvBiADLx0oH0AGOBhFCBcDPgsXCAkGCgsKDAgEBBIDESQJMhEm
        BEsCJgVLCRsMLwYgBC8dKCBABTgYRQkXAj4LFwkJBQoMCgsIBQQKAwIEBQMRJAoyECYDSwMmBEsJGwwvBCAGLx4oIUAEOBhFFxcICQUKDQoKCAYECQMDBAMD
        AQQRJAoyECYCSwUmCxsWLx8oIkADOBhFFxcJCQQKDQoKCAYECAMIBBEkCzIWJgkbGC8eKCRAAjgXRRgXBAkCDgMJBAoOCgkIBwQGAwkEESQMMhUmCBsYLx4o
        JkABOAFFBEARRRkXBAkDDgQJAgoOCgkIBwQGAwkEECQPMhImAjADGwMwGC8eKC5ADkUbFwUJAw4DCQIKDgoJCAcEBgMJBBAkAjICJAsyEiYIMBgvHSgEPSxA
        DEUdFwUJAw4DCQEKDwoJCAcEBgMJBBMkDDIPJgowGC8dKAc9KUALRRkXAg4DFwUJAw4ECQ8KCQgIBAQDCgQUJAwyDSYKMBkvHCgLPSZADEUYFwMOAhcFCQQO
        AwkCCQ0KCQgWBBQkDDINJgowGS8bKA49JUALRQgXATsPFwQOBgkFDgIJAgkNCggIAQYWBBUkCzIMJgowGS8SKBk9JEALRQE7BRcEOw4XBQ4FCQUOAgkDCQwK
        BwgDBhYEFCQLMgwmCjAYLxIoGj0jQApFAQADOwMXBjsOFwUOAwkHDgEJBAkLCgYIBQYVBBQkCjIGHQUmDDAZLxAoGz0jQAlFAgAMOw8XDg4BCQYJCQoDBwEI
        CAYTBBUkCTIJHQMmCzAbLw8oGz0jQAdFAwAOOw4XDw4HCQgKBAcJBhIEFCQBKgkyCh0BJgwwKC8dPQpAA0kWQAdFAgAPOw4XDw4BDgcJBgoGBwkGEgQTJAMq
        BzIKHQ0wKS8dPQZACUkSQAdFAwAROwsXAQ8PDgIOCQkDCgYHCgYBBRAEBiQBKgckAioDJAUqBjIKHQswKC8fPQRADUkRQAZFAgASOwoXAw8ODgIOCgkIBwoG
        BAUDBAIFCAQFJAQqBCQRKgkdDDAoLx89AkAPSRNAA0UDABM7BxcGDw0OAg4KCQgHCgYKBQUEAgUFJBkqCB0NMCcvID0TSRJAAUUDABQ7BhcIDwwOAw4JCQgH
        CgYJBQQEBAUEJB4qBB0MMCcvID0USRJABAAVOwUXCA8MDgQOBwkBBgcHDAYJBQIEBgUDJB4qAh0OMCcvID0VSRFAAwAWOwYXCA8LDgQOBgkEBgUHDwYQBSAq
        EDAkLyI9FkkQQAQAFzsEFwgPCw4EDgUJBgYDBxEGEAUgKg8wJC8hPRdJEEADABg7AxcLDwkOBQ4ECRoGEQUfKg4wJC8hPRlJDkADABs7Dg8HDgUOAgkbBhIF
        HyoOMCMvIT0aSQ1ABAAbOw8PBg4GDhsGFAUdKg8wIy8gPRxJDUADABs7EA8FDgcOGgYUBRwqEDAiLyA9HUkMQAQAGzsSDwMOBw4bBhMFGyoRMCEvID0fSQtA
        BAAbOxMPAg4HDhwGEwUINRAqEjAhLyE9I0kGQAQAHDsTDwIOCA4cBhMFCTUMKhUwHy8iPRRJATkOSQZABQAcOxMPAQ4KDhsGAgUQGQs1HzAdLyQ9AzkPSQM5
        DkkHQAMAHDsVDwsOGgYTGQs1HjAcLyQ9BzkKSQY5EEkDQAQAHDsVDwsOGQYUGQs1HjAbLyU9BjkKSQc5EkkBQAQAHTsUDwIPCQ4XBhcZCzUeMBgvDT0CJRg9
        BzkJSQg5EkkEAB07FA8FDwcOFQYZGQs1FzAGTBYvAiUMPQQlFz0HOQpJBzkSSQMAHTsVDwYPBg4TBhsZDDULMAdMAjAITBQvBCUMPQYlFD0IOQlJCDkRSQQA
        HTsVDwgPBg4PBh0ZDjUIMBRMEC8GJQs9ByUUPQo5CUkHORBJBAAeOxQPCg8FDgwGHhkRNRtMDC8JJQs9ByUVPQk5CUkMOQtJBAAeOxQPCw8FDggGIRkSNRtM
        FSUKPQclFD0LOQdJDTkLSQQAHjsUDwsPBg4EBiQZAi0RNRpMGiUFPQclFT0eOQtJBAAUOwoWFA8NDwMOKBkFLQ81GkwaJQU9ByUVPR45C0kEABE7EBYRDw4P
        KBkILQ41G0waJQU9BiUVPR45C0kEAA87FRYODw4PJhkMLQw1G0wcJQM9ByUVPSE5BkkFAA47GBYMDw4PIhkRLQs1G0woJRJDIzkFSQQADTscFgoPDg8gGRUt
        CTUbTCclFkMnOQMADDseFggPDg8fGRYtCjUbTCYlF0MmOQMACzsgFgcPDQ8eGRktCjUTTAIlBUwmJRdDJjkEAAk7JRYDDw0PHhkaLQk1EUwGJQRMJSUZQyM5
        BAAKOygWARYMDx0ZHC0KNQ9MByUDTCYlGUMPOQFDEjkGAAg7KBYEFgkPHRkdLQs1C0wKJQNMJSUcQws5A0MROQYABjsqFgUWBw8cGR8tFDU0JSpDETkGAAU7
        KxYHFgYPGhkhLRQ1MyUrQxA5CQAtFggWBA8aGSItFDU0JSlDEDkJAC4WCxYaGSQtFDUzJSpDBjkDQwc5CAAuFgsWGRklLRQ1MyUqQwU5BUMFOQkALhYJFhgZ
        KC0UNTMlKkMEOQdDAzkJAC8WChYXGSktFDUzJThDCQAuFggWGBkpLRU1MiU4QwoALhYIFhYZAxYnLRc1MSU3QwsALhYIFhUZBRYmLRc1MiU2QwsALhYJFhEZ
        ChYkLRc1MiU2QwsALhYNFgkZDxYjLRg1MiU1QwwALRYnFiItFzUyJTVDCwAuFigWHy0WADUlNkMMACwWKRYTLQIACC0aADMlM0MOACwWKxYRLQUABi0ZADMl
        NEMOACsWLBYNLQgABS0ZADUlM0MOACsWLxYKLQgABi0ZADQlNEMOACoWMBYJLQgABS1SADFDDwAoFjMWBi0IAAYtVwAsQw4AKBY0FgMtCgAFLVkAK0MQACYW
        OBZrAChDDwAmFjcWbAApQxAAJBY0Fm4AKkMQACQWNBZwAClDEQAiFjMWdAAoQw8AIhY=
        """;

    public static ReadOnlySpan<byte> Cells => CellsData;

    public static byte GetSpiceField(byte mapX, byte mapY)
    {
        var row = mapY > 180 ? mapY - 180 : mapY + 75;
        if (row >= Height)
        {
            throw new ArgumentOutOfRangeException(nameof(mapY), mapY, "Map Y must encode a latitude from -75 through 75.");
        }

        return CellsData[(row * Width) + mapX];
    }

    private static byte[] Decode()
    {
        var runs = Convert.FromBase64String(EncodedRuns);
        var cells = GC.AllocateUninitializedArray<byte>(Width * Height);
        var destination = 0;

        for (var source = 0; source < runs.Length; source += 2)
        {
            var length = runs[source] == 0 ? Width : runs[source];
            cells.AsSpan(destination, length).Fill(runs[source + 1]);
            destination += length;
        }

        if (destination != cells.Length)
        {
            throw new InvalidDataException("The embedded Dune map-zone data is incomplete.");
        }

        PatchNorthAntimeridianGap(cells);
        return cells;
    }

    private static void PatchNorthAntimeridianGap(byte[] cells)
    {
        // The reconstructed DUNEPRG projection leaves longitude 255 blank at
        // the north cap even though the matching shape continues through
        // longitude 0. Fill that one-cell discontinuity for toroidal rendering.
        for (var row = 0; row <= 20; row++)
        {
            var lastCell = ((row + 1) * Width) - 1;
            cells[lastCell] = cells[lastCell - 1];
        }
    }
}
