// -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        The WPF ShaderEffect Generator
//        http://wpfshadergenerator.codeplex.com
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace DuneEdit
{
    using System;
    using System.Windows;
    using System.Windows.Media;
    using System.Windows.Media.Effects;
    using System.Windows.Media.Media3D;
    
    
    /// <summary>A simple color blending shader for WPF.</summary>
    public class SelectionEffect : System.Windows.Media.Effects.ShaderEffect
    {
        
        /// <summary>The brightness offset.</summary>
        public static readonly DependencyProperty GlowColorProperty = DependencyProperty.Register("GlowColor", typeof(System.Windows.Media.Color), typeof(SelectionEffect), new PropertyMetadata(Color.FromArgb(0,0,0,0), PixelShaderConstantCallback(0)));
        /// <summary>The center of the blur.</summary>
        public static readonly DependencyProperty CenterProperty = DependencyProperty.Register("Center", typeof(System.Windows.Point), typeof(SelectionEffect), new PropertyMetadata(new Point(0.5,0.5), PixelShaderConstantCallback(1)));
        /// <summary>The amount of blur.</summary>
        public static readonly DependencyProperty BlurAmountProperty = DependencyProperty.Register("BlurAmount", typeof(System.Double), typeof(SelectionEffect), new PropertyMetadata((double)0.15, PixelShaderConstantCallback(2)));
        /// <summary>The size of the glowing halo.</summary>
        public static readonly DependencyProperty GlowSizeProperty = DependencyProperty.Register("GlowSize", typeof(System.Double), typeof(SelectionEffect), new PropertyMetadata((double)0.1, PixelShaderConstantCallback(3)));
        /// <summary>The intensity of inner (non-halo) glow.</summary>
        public static readonly DependencyProperty InnerGlowProperty = DependencyProperty.Register("InnerGlow", typeof(System.Double), typeof(SelectionEffect), new PropertyMetadata((double)0.1, PixelShaderConstantCallback(4)));
        /// <summary>The implicit input sampler passed into the pixel shader by WPF.</summary>
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(SelectionEffect), 0, SamplingMode.Auto);
        
        public SelectionEffect()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("/DuneEdit;component/SelectionEffect.ps", UriKind.Relative);
            this.PixelShader = pixelShader;
            this.UpdateShaderValue(GlowColorProperty);
            this.UpdateShaderValue(CenterProperty);
            this.UpdateShaderValue(BlurAmountProperty);
            this.UpdateShaderValue(GlowSizeProperty);
            this.UpdateShaderValue(InnerGlowProperty);
            this.UpdateShaderValue(InputProperty);
            this.DdxUvDdyUvRegisterIndex = -1;
        }
        
        /// <summary>The brightness offset.</summary>
        public virtual System.Windows.Media.Color GlowColor
        {
            get
            {
                return ((System.Windows.Media.Color)(this.GetValue(GlowColorProperty)));
            }
            set
            {
                this.SetValue(GlowColorProperty, value);
            }
        }
        
        /// <summary>The center of the blur.</summary>
        public virtual System.Windows.Point Center
        {
            get
            {
                return ((System.Windows.Point)(this.GetValue(CenterProperty)));
            }
            set
            {
                this.SetValue(CenterProperty, value);
            }
        }
        
        /// <summary>The amount of blur.</summary>
        public virtual double BlurAmount
        {
            get
            {
                return ((double)(this.GetValue(BlurAmountProperty)));
            }
            set
            {
                this.SetValue(BlurAmountProperty, value);
            }
        }
        
        /// <summary>The size of the glowing halo.</summary>
        public virtual double GlowSize
        {
            get
            {
                return ((double)(this.GetValue(GlowSizeProperty)));
            }
            set
            {
                this.SetValue(GlowSizeProperty, value);
            }
        }
        
        /// <summary>The intensity of inner (non-halo) glow.</summary>
        public virtual double InnerGlow
        {
            get
            {
                return ((double)(this.GetValue(InnerGlowProperty)));
            }
            set
            {
                this.SetValue(InnerGlowProperty, value);
            }
        }
        
        /// <summary>The implicit input sampler passed into the pixel shader by WPF.</summary>
        public virtual System.Windows.Media.Brush Input
        {
            get
            {
                return ((System.Windows.Media.Brush)(this.GetValue(InputProperty)));
            }
            set
            {
                this.SetValue(InputProperty, value);
            }
        }
    }
}
